# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :android do


  desc "Generate a new local APK"
  lane :build do
    ENV["ENVFILE"]=".env.production"

    gradle(
      project_dir: './android',
      task: 'assemble',
      flavor: 'Production',
      build_type: 'Release',
    )
  end

  desc "Generate a new local APK for testing"
  lane :build_internal do
    ENV["ENVFILE"]=".env.staging"

    gradle(
        project_dir: './android',
        task: 'assemble',
        flavor: 'Staging',
        build_type: 'Release',
    )
  end


  desc "Build and upload app to Google Play"
  lane :beta do
    ENV["ENVFILE"]=".env.production"
    # Google is very unreliable, so we retry a few times
    ENV["SUPPLY_UPLOAD_MAX_RETRIES"]="5"

    gradle(
        project_dir: './android',
        task: 'bundle',
        flavor: 'Production',
        build_type: 'Release',
    )

    upload_to_play_store(
        package_name: "com.alcohol_tracker",
        json_key: './android/app/android-fastlane-json-key.json',
        aab: './android/app/build/outputs/bundle/productionRelease/app-production-release.aab',
        track: 'internal',
        rollout: '1.0',
        skip_upload_apk: true,
    )
  end


  desc "Deploy app to Google Play open beta"
  lane :production do
    # Google is very unreliable, so we retry a few times
    ENV["SUPPLY_UPLOAD_MAX_RETRIES"]="5"
    google_play_track_version_codes(
      package_name: "com.alcohol_tracker",
      json_key: './android/app/android-fastlane-json-key.json',
      track: 'beta' # modify to 'production' when ready
    )

    upload_to_play_store(
      package_name: "com.alcohol_tracker",
      json_key: './android/app/android-fastlane-json-key.json',
      version_code: ENV["VERSION"].to_i,
      track: 'internal',
      track_promote_to: 'beta', # Modify to production when ready
      rollout: '1.0',
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end

platform :ios do
  desc "Generate a local iOS production build"
  lane :build do
    # ENV["ENVFILE"]=".env.production"
    build_app(workspace: "./ios/kiroku.xcworkspace", scheme: "kiroku")
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "./ios/kiroku.xcodeproj")
    build_app(workspace: "./ios/kiroku.xcworkspace", scheme: "kiroku")
    upload_to_testflight
  end
end
