// Taken and modified form the Expensify GitHub
// Source: https://github.com/Expensify/App/blob/main/src/CONST.ts

// import Config from 'react-native-config';

// Creating a default array and object this way because objects ({}) and arrays ([]) are not stable types.
// Freezing the array ensures that it cannot be unintentionally modified.
const EMPTY_ARRAY = Object.freeze([]);
const EMPTY_OBJECT = Object.freeze({});

const ANDROID_PACKAGE_NAME = 'com.alcohol_tracker';
const GH_PAGES_URL = 'https://petrcala.github.io/Kiroku';

const CONST = {
  ACCOUNT_CREATION_LIMIT: 3,
  ANDROID_PACKAGE_NAME,
  ANIMATED_TRANSITION: 300,
  ANIMATED_TRANSITION_FROM_VALUE: 100,
  ANIMATION_IN_TIMING: 100,
  ANIMATION_DIRECTION: {
    IN: 'in',
    OUT: 'out',
  },
  APP_DOWNLOAD_LINK: `${GH_PAGES_URL}/assets/html/qr-link.html`,
  APP_QR_CODE_LINK: `${GH_PAGES_URL}/assets/images/kiroku-qr-code-with-logo.png`,
  PRIVACY_POLICY_URL: `${GH_PAGES_URL}/assets/html/privacy-policy.html`,
  TERMS_OF_SERVICE_URL: `${GH_PAGES_URL}/assets/html/terms-of-service.html`,
  API_REQUEST_TYPE: {
    READ: 'read',
    WRITE: 'write',
    MAKE_REQUEST_WITH_SIDE_EFFECTS: 'makeRequestWithSideEffects',
  },
  AUTO_AUTH_STATE: {
    NOT_STARTED: 'not-started',
    SIGNING_IN: 'signing-in',
    JUST_SIGNED_IN: 'just-signed-in',
    FAILED: 'failed',
  },
  APP_STATE: {
    ACTIVE: 'active',
    BACKGROUND: 'background',
    INACTIVE: 'inactive',
  },
  APP_IN_BETA: true,
  AUTH_TOKEN_TYPES: {
    ANONYMOUS: 'anonymousAccount',
    SUPPORT: 'support',
  },
  AVAILABLE_PLATFORMS: ['ios', 'android'],
  AVATAR_SIZE: {
    XLARGE: 'xlarge',
    LARGE: 'large',
    MEDIUM: 'medium',
    DEFAULT: 'default',
    SMALL: 'small',
    SMALLER: 'smaller',
    SUBSCRIPT: 'subscript',
    SMALL_SUBSCRIPT: 'small-subscript',
    MID_SUBSCRIPT: 'mid-subscript',
    LARGE_BORDERED: 'large-bordered',
    HEADER: 'header',
    MENTION_ICON: 'mention-icon',
    SMALL_NORMAL: 'small-normal',
  },
  BROWSER: {
    CHROME: 'chrome',
    FIREFOX: 'firefox',
    IE: 'ie',
    EDGE: 'edge',
    Opera: 'opera',
    SAFARI: 'safari',
    OTHER: 'other',
  },
  BUTTON_STATES: {
    DEFAULT: 'default',
    ACTIVE: 'active',
    PRESSED: 'pressed',
    COMPLETE: 'complete',
    DISABLED: 'disabled',
  },
  CACHE: {
    PROFILE_PICTURE_KEY: 'profilePicture',
  },
  COLOR_SCHEME: {
    LIGHT: 'light',
    DARK: 'dark',
  },
  COUNTRY: {
    US: 'US',
    CZ: 'CZ',
  },
  DATE: {
    SQL_DATE_TIME: 'YYYY-MM-DD HH:mm:ss',
    FNS_FORMAT_STRING: 'yyyy-MM-dd',
    LOCAL_TIME_FORMAT: 'h:mm a',
    YEAR_MONTH_FORMAT: 'yyyyMM',
    MONTH_FORMAT: 'MMMM',
    WEEKDAY_TIME_FORMAT: 'eeee',
    MONTH_DAY_ABBR_FORMAT: 'MMM d',
    SHORT_DATE_FORMAT: 'MM-dd',
    MONTH_DAY_YEAR_ABBR_FORMAT: 'MMM d, yyyy',
    MONTH_DAY_YEAR_FORMAT: 'MMMM d, yyyy',
    FNS_TIMEZONE_FORMAT_STRING: "yyyy-MM-dd'T'HH:mm:ssXXX",
    FNS_DB_FORMAT_STRING: 'yyyy-MM-dd HH:mm:ss.SSS',
    LONG_DATE_FORMAT_WITH_WEEKDAY: 'eeee, MMMM d, yyyy',
    UNIX_EPOCH: '1970-01-01 00:00:00.000',
    MAX_DATE: '9999-12-31',
    MIN_DATE: '0001-01-01',
    ORDINAL_DAY_OF_MONTH: 'do',
  },
  DEBUG_CONSOLE: {
    LEVELS: {
      INFO: 'INFO',
      ERROR: 'ERROR',
      RESULT: 'RESULT',
      DEBUG: 'DEBUG',
    },
  },
  DIRECTION: {
    LEFT: 'left',
    RIGHT: 'right',
  },
  DROPDOWN_BUTTON_SIZE: {
    LARGE: 'large',
    MEDIUM: 'medium',
  },
  ENVIRONMENT: {
    DEV: 'development',
    STAGING: 'staging',
    PROD: 'production',
    TEST: 'test',
  },
  EMPTY_ARRAY,
  EMPTY_OBJECT,
  ERROR: {
    XHR_FAILED: 'xhrFailed',
    THROTTLED: 'throttled',
    UNKNOWN_ERROR: 'Unknown error',
    REQUEST_CANCELLED: 'AbortError',
    FAILED_TO_FETCH: 'Failed to fetch',
    ENSURE_BUGBOT: 'ENSURE_BUGBOT',
    PUSHER_ERROR: 'PusherError',
    WEB_SOCKET_ERROR: 'WebSocketError',
    NETWORK_REQUEST_FAILED: 'Network request failed',
    SAFARI_DOCUMENT_LOAD_ABORTED: 'cancelled',
    FIREFOX_DOCUMENT_LOAD_ABORTED:
      'NetworkError when attempting to fetch resource.',
    IOS_NETWORK_CONNECTION_LOST: 'The network connection was lost.',
    IOS_NETWORK_CONNECTION_LOST_CZECH: 'Spojení bylo ztraceno.',
    IOS_LOAD_FAILED: 'Load failed',
    SAFARI_CANNOT_PARSE_RESPONSE: 'cannot parse response',
    GATEWAY_TIMEOUT: 'Gateway Timeout',
    EXPENSIFY_SERVICE_INTERRUPTED: 'Expensify service interrupted',
    DUPLICATE_RECORD: 'A record already exists with this ID',

    // The "Upgrade" is intentional as the 426 HTTP code means "Upgrade Required" and sent by the API. We use the "Update" language everywhere else in the front end when this gets returned.
    UPDATE_REQUIRED: 'Upgrade Required',
  },
  FIREBASE_STORAGE_URL: 'https://firebasestorage.googleapis.com',
  FRIEND_REQUEST_STATUS: {
    SELF: 'self',
    SENT: 'sent',
    RECEIVED: 'received',
    FRIEND: 'friend',
    UNDEFINED: 'undefined',
  },
  INVALID_CHARS: ['.', '#', '$', '[', ']'],
  LOCAL_IMAGE_PREFIX: 'file://',
  LOCALES: {
    EN: 'en',
    CS_CZ: 'cs_CZ',

    DEFAULT: 'en',
  },
  MAX_ALLOWED_UNITS: 100,
  MONTHS: [
    'January',
    'February',
    'March',
    'April',
    'May',
    'June',
    'July',
    'August',
    'September',
    'October',
    'November',
    'December',
  ],
  MONTHS_ABBREVIATED: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'May',
    'Jun',
    'Jul',
    'Aug',
    'Sep',
    'Oct',
    'Nov',
    'Dec',
  ],
  NAVIGATION: {
    TYPE: {
      FORCED_UP: 'FORCED_UP',
      UP: 'UP',
    },
    ACTION_TYPE: {
      REPLACE: 'REPLACE',
      PUSH: 'PUSH',
      NAVIGATE: 'NAVIGATE',
    },
    SESSION_ACTION: {
      SAVE: 'SAVE',
      DISCARD: 'DISCARD',
    },
  },
  NETWORK: {
    METHOD: {
      POST: 'post',
    },
    MIN_RETRY_WAIT_TIME_MS: 10,
    MAX_RANDOM_RETRY_WAIT_TIME_MS: 100,
    MAX_RETRY_WAIT_TIME_MS: 10 * 1000,
    PROCESS_REQUEST_DELAY_MS: 1000,
    MAX_PENDING_TIME_MS: 10 * 1000,
    MAX_REQUEST_RETRIES: 10,
  },
  DEFAULT_NETWORK_DATA: {isOffline: false},
  NO_IMAGE: 'NO_IMAGE', // Used for the profile avatar when there is no image
  ONYX_UPDATE_TYPES: {
    HTTPS: 'https',
    PUSHER: 'pusher',
    AIRSHIP: 'airship',
  },
  OS: {
    WINDOWS: 'Windows',
    MAC_OS: 'Mac OS',
    ANDROID: 'Android',
    IOS: 'iOS',
    LINUX: 'Linux',
    NATIVE: 'Native',
  },
  PLATFORM: {
    IOS: 'iOS',
    ANDROID: 'Android',
    WEB: 'Web',
  },
  PUSHER: {
    PRIVATE_USER_CHANNEL_PREFIX: 'private-encrypted-user-accountID-',
  },
  REGEX: {
    ROUTES: {
      REDUNDANT_SLASHES: /(\/{2,})|(\/$)/g,
    },
    // DATE_TIME_FORMAT: /^\d{2}-\d{2} \d{2}:\d{2} [AP]M$/,
  },
  SESSION_EXPIRY: 60 * 60 * 1000 * 12, // 12 hours
  SESSION_TYPES: {
    LIVE: 'live',
    EDIT: 'edit',
  },
  SOCIALS: {
    TWITTER: '',
    INSTAGRAM: '',
    FACEBOOK: '',
    LINKEDIN: '',
  },
  STATUS_BAR_STYLE: {
    LIGHT_CONTENT: 'light-content',
    DARK_CONTENT: 'dark-content',
  },
  STORE_LINKS: {
    ANDROID:
      'https://play.google.com/store/apps/details?id=com.alcohol_tracker',
    IOS: 'https://testflight.apple.com/join/DgY9IieL',
  },
  THEME: {
    DEFAULT: 'system',
    FALLBACK: 'dark',
    DARK: 'dark',
    LIGHT: 'light',
    SYSTEM: 'system',
  },
  TIMING: {
    HOMEPAGE_INITIAL_RENDER: 'homepage_initial_render',
    SEARCH_RENDER: 'search_render',
    COLD: 'cold',
    WARM: 'warm',
    COMMENT_LENGTH_DEBOUNCE_TIME: 500,
    SEARCH_OPTION_LIST_DEBOUNCE_TIME: 300,
    RESIZE_DEBOUNCE_TIME: 100,
  },
  TIME_PERIOD: {
    AM: 'AM',
    PM: 'PM',
  },
  DRINKS: {
    // Perhaps move to types?
    KEYS: {
      SMALL_BEER: 'small_beer',
      BEER: 'beer',
      COCKTAIL: 'cocktail',
      OTHER: 'other',
      STRONG_SHOT: 'strong_shot',
      WEAK_SHOT: 'weak_shot',
      WINE: 'wine',
    },
    NAMES: {
      SMALL_BEER: 'Small Beer',
      BEER: 'Beer',
      COCKTAIL: 'Cocktail',
      OTHER: 'Other',
      STRONG_SHOT: 'Strong Shot',
      WEAK_SHOT: 'Weak Shot',
      WINE: 'Wine',
    },
  },

  ALL_COUNTRIES: {
    AF: 'Afghanistan',
    AX: 'Åland Islands',
    AL: 'Albania',
    DZ: 'Algeria',
    AS: 'American Samoa',
    AD: 'Andorra',
    AO: 'Angola',
    AI: 'Anguilla',
    AQ: 'Antarctica',
    AG: 'Antigua & Barbuda',
    AR: 'Argentina',
    AM: 'Armenia',
    AW: 'Aruba',
    AC: 'Ascension Island',
    AU: 'Australia',
    AT: 'Austria',
    AZ: 'Azerbaijan',
    BS: 'Bahamas',
    BH: 'Bahrain',
    BD: 'Bangladesh',
    BB: 'Barbados',
    BY: 'Belarus',
    BE: 'Belgium',
    BZ: 'Belize',
    BJ: 'Benin',
    BM: 'Bermuda',
    BT: 'Bhutan',
    BO: 'Bolivia',
    BA: 'Bosnia & Herzegovina',
    BW: 'Botswana',
    BR: 'Brazil',
    IO: 'British Indian Ocean Territory',
    VG: 'British Virgin Islands',
    BN: 'Brunei',
    BG: 'Bulgaria',
    BF: 'Burkina Faso',
    BI: 'Burundi',
    KH: 'Cambodia',
    CM: 'Cameroon',
    CA: 'Canada',
    CV: 'Cape Verde',
    BQ: 'Caribbean Netherlands',
    KY: 'Cayman Islands',
    CF: 'Central African Republic',
    TD: 'Chad',
    CL: 'Chile',
    CN: 'China',
    CX: 'Christmas Island',
    CC: 'Cocos (Keeling) Islands',
    CO: 'Colombia',
    KM: 'Comoros',
    CG: 'Congo - Brazzaville',
    CD: 'Congo - Kinshasa',
    CK: 'Cook Islands',
    CR: 'Costa Rica',
    CI: "Côte d'Ivoire",
    HR: 'Croatia',
    CU: 'Cuba',
    CW: 'Curaçao',
    CY: 'Cyprus',
    CZ: 'Czech Republic',
    DK: 'Denmark',
    DJ: 'Djibouti',
    DM: 'Dominica',
    DO: 'Dominican Republic',
    EC: 'Ecuador',
    EG: 'Egypt',
    SV: 'El Salvador',
    GQ: 'Equatorial Guinea',
    ER: 'Eritrea',
    EE: 'Estonia',
    ET: 'Ethiopia',
    FK: 'Falkland Islands',
    FO: 'Faroe Islands',
    FJ: 'Fiji',
    FI: 'Finland',
    FR: 'France',
    GF: 'French Guiana',
    PF: 'French Polynesia',
    TF: 'French Southern Territories',
    GA: 'Gabon',
    GM: 'Gambia',
    GE: 'Georgia',
    DE: 'Germany',
    GH: 'Ghana',
    GI: 'Gibraltar',
    GR: 'Greece',
    GL: 'Greenland',
    GD: 'Grenada',
    GP: 'Guadeloupe',
    GU: 'Guam',
    GT: 'Guatemala',
    GG: 'Guernsey',
    GN: 'Guinea',
    GW: 'Guinea-Bissau',
    GY: 'Guyana',
    HT: 'Haiti',
    HN: 'Honduras',
    HK: 'Hong Kong',
    HU: 'Hungary',
    IS: 'Iceland',
    IN: 'India',
    ID: 'Indonesia',
    IR: 'Iran',
    IQ: 'Iraq',
    IE: 'Ireland',
    IM: 'Isle of Man',
    IL: 'Israel',
    IT: 'Italy',
    JM: 'Jamaica',
    JP: 'Japan',
    JE: 'Jersey',
    JO: 'Jordan',
    KZ: 'Kazakhstan',
    KE: 'Kenya',
    KI: 'Kiribati',
    XK: 'Kosovo',
    KW: 'Kuwait',
    KG: 'Kyrgyzstan',
    LA: 'Laos',
    LV: 'Latvia',
    LB: 'Lebanon',
    LS: 'Lesotho',
    LR: 'Liberia',
    LY: 'Libya',
    LI: 'Liechtenstein',
    LT: 'Lithuania',
    LU: 'Luxembourg',
    MO: 'Macau',
    MK: 'Macedonia',
    MG: 'Madagascar',
    MW: 'Malawi',
    MY: 'Malaysia',
    MV: 'Maldives',
    ML: 'Mali',
    MT: 'Malta',
    MH: 'Marshall Islands',
    MQ: 'Martinique',
    MR: 'Mauritania',
    MU: 'Mauritius',
    YT: 'Mayotte',
    MX: 'Mexico',
    FM: 'Micronesia',
    MD: 'Moldova',
    MC: 'Monaco',
    MN: 'Mongolia',
    ME: 'Montenegro',
    MS: 'Montserrat',
    MA: 'Morocco',
    MZ: 'Mozambique',
    MM: 'Myanmar (Burma)',
    NA: 'Namibia',
    NR: 'Nauru',
    NP: 'Nepal',
    NL: 'Netherlands',
    NC: 'New Caledonia',
    NZ: 'New Zealand',
    NI: 'Nicaragua',
    NE: 'Niger',
    NG: 'Nigeria',
    NU: 'Niue',
    NF: 'Norfolk Island',
    KP: 'North Korea',
    MP: 'Northern Mariana Islands',
    NO: 'Norway',
    OM: 'Oman',
    PK: 'Pakistan',
    PW: 'Palau',
    PS: 'Palestinian Territories',
    PA: 'Panama',
    PG: 'Papua New Guinea',
    PY: 'Paraguay',
    PE: 'Peru',
    PH: 'Philippines',
    PN: 'Pitcairn Islands',
    PL: 'Poland',
    PT: 'Portugal',
    PR: 'Puerto Rico',
    QA: 'Qatar',
    RE: 'Réunion',
    RO: 'Romania',
    RU: 'Russia',
    RW: 'Rwanda',
    BL: 'Saint Barthélemy',
    WS: 'Samoa',
    SM: 'San Marino',
    ST: 'São Tomé & Príncipe',
    SA: 'Saudi Arabia',
    SN: 'Senegal',
    RS: 'Serbia',
    SC: 'Seychelles',
    SL: 'Sierra Leone',
    SG: 'Singapore',
    SX: 'Sint Maarten',
    SK: 'Slovakia',
    SI: 'Slovenia',
    SB: 'Solomon Islands',
    SO: 'Somalia',
    ZA: 'South Africa',
    GS: 'South Georgia & South Sandwich Islands',
    KR: 'South Korea',
    SS: 'South Sudan',
    ES: 'Spain',
    LK: 'Sri Lanka',
    SH: 'St. Helena',
    KN: 'St. Kitts & Nevis',
    LC: 'St. Lucia',
    MF: 'St. Martin',
    PM: 'St. Pierre & Miquelon',
    VC: 'St. Vincent & Grenadines',
    SD: 'Sudan',
    SR: 'Suriname',
    SJ: 'Svalbard & Jan Mayen',
    SZ: 'Swaziland',
    SE: 'Sweden',
    CH: 'Switzerland',
    SY: 'Syria',
    TW: 'Taiwan',
    TJ: 'Tajikistan',
    TZ: 'Tanzania',
    TH: 'Thailand',
    TL: 'Timor-Leste',
    TG: 'Togo',
    TK: 'Tokelau',
    TO: 'Tonga',
    TT: 'Trinidad & Tobago',
    TA: 'Tristan da Cunha',
    TN: 'Tunisia',
    TR: 'Turkey',
    TM: 'Turkmenistan',
    TC: 'Turks & Caicos Islands',
    TV: 'Tuvalu',
    UM: 'U.S. Outlying Islands',
    VI: 'U.S. Virgin Islands',
    UG: 'Uganda',
    UA: 'Ukraine',
    AE: 'United Arab Emirates',
    GB: 'United Kingdom',
    US: 'United States',
    UY: 'Uruguay',
    UZ: 'Uzbekistan',
    VU: 'Vanuatu',
    VA: 'Vatican City',
    VE: 'Venezuela',
    VN: 'Vietnam',
    WF: 'Wallis & Futuna',
    EH: 'Western Sahara',
    YE: 'Yemen',
    ZM: 'Zambia',
    ZW: 'Zimbabwe',
  },
} as const;

type Country = keyof typeof CONST.ALL_COUNTRIES;

export type {Country};

export default CONST;
